version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.3
    - 4.2.4
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: knex
    versions:
    - 0.21.17
    - 0.21.18
    - 0.95.0
    - 0.95.1
    - 0.95.3
    - 0.95.4
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: globby
    versions:
    - 11.0.3
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.21.0
    - 4.22.0
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.2
    - 26.5.4
  - dependency-name: telegraf
    versions:
    - 4.0.2
    - 4.0.3
    - 4.1.0
    - 4.1.1
    - 4.1.2
    - 4.2.0
    - 4.2.1
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.11
    - 13.0.7
    - 13.0.9
  - dependency-name: quick-lru
    versions:
    - 6.0.0
  - dependency-name: "@types/tunnel"
    versions:
    - 0.0.2
  - dependency-name: lockfile-lint
    versions:
    - 4.6.0
  - dependency-name: camaro
    versions:
    - 6.1.0
  - dependency-name: node-schedule
    versions:
    - 1.3.3
    - 2.0.0
  - dependency-name: fastq
    versions:
    - 1.10.1
  - dependency-name: escape-goat
    versions:
    - 4.0.0
  - dependency-name: clean-stack
    versions:
    - 4.0.0
  - dependency-name: js-yaml
    versions:
    - 4.1.0
  - dependency-name: pg
    versions:
    - 8.6.0
  - dependency-name: winston-daily-rotate-file
    versions:
    - 4.5.2
  - dependency-name: "@vercel/nft"
    versions:
    - 0.10.0
