name: Test Docker build
on:
    - pull_request_target

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to DockerHub
              if: ${{ github.ref == 'refs/heads/master' }}
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: output-docker-tag
              shell: bash
              id: docker-tag
              run: |
                  unset BRANCH_NAME
                  echo $GITHUB_REF_NAME
                  BRANCH_NAME=`echo $GITHUB_REF_NAME`
                  echo "BRANCH_NAME: $BRANCH_NAME"
                  unset IMG_TAGS ; if [[ $BRANCH_NAME == "master" ]]; then IMG_TAGS='latest' ; else IMG_TAGS="$BRANCH_NAME"; fi
                  SHA_TAG=`echo $GITHUB_SHA | head -c 6`
                  echo "SHA_TAG: $SHA_TAG"
                  echo "DOCKER_BRANCH_TAG=${IMG_TAGS}" >> $GITHUB_OUTPUT
                  echo "DOCKER_SHA_TAG=${SHA_TAG}" >> $GITHUB_OUTPUT
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: false
                  tags: fengkx/node_rssbot:${{steps.docker-tag.outputs.DOCKER_BRANCH_TAG}},fengkx/node_rssbot:${{steps.docker-tag.outputs.DOCKER_SHA_TAG}}
